# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

# invalidArgs
POST http://localhost:8080/albums/test-user/create
Content-Type: application/x-www-form-urlencoded

title=NewAlbum&image=random.png&year=1950

###

# invalidArgs
POST http://localhost:8080/albums/test-user/create
Content-Type: application/x-www-form-urlencoded

token=g2xoxjg2kbu2sdwa&image=random.png&year=1950

###

# unknownUser
POST http://localhost:8080/albums/invalid-user/create
Content-Type: application/x-www-form-urlencoded

token=g2xoxjg2kbu2sdwa&title=NewAlbum&image=random.png&year=1950

###

# invalidToken
POST http://localhost:8080/albums/test-user/create
Content-Type: application/x-www-form-urlencoded

token=invalid-g2xoxjg2kbu2sdwa&title=NewAlbum&image=random.png&year=1950

###

#invalidImage
POST http://localhost:8080/albums/test-user/create
Content-Type: application/x-www-form-urlencoded

token=g2xoxjg2kbu2sdwa&title=NewAlbum&year=1950

###

# invalidYear
POST http://localhost:8080/albums/test-user/create
Content-Type: application/x-www-form-urlencoded

token=g2xoxjg2kbu2sdwa&title=NewAlbum&image=random.png&year=1850

###

POST http://localhost:8080/albums/test-user/create
Content-Type: application/x-www-form-urlencoded

token=g2xoxjg2kbu2sdwa&title=NewAlbum&image=random.png&year=1950

###